import test from 'node:test';
import assert from 'node:assert/strict';
import * as E from '../src/engine.mjs';
const H=3600000;
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`);
test('Manufacturer defaults contain duration but no invented kWh',()=>{assert.deepEqual(E.DEFAULT_PROGRAMS.map(x=>x.minutes),[810,510,390,460]);assert.ok(E.DEFAULT_PROGRAMS.every(x=>x.kwh===null));});
test('Fixed total: 30 kWh at DKK 2 = DKK 60',()=>{const r=E.calculate(0,{minutes:390,kwh:30},[{start:0,end:8*H,price:2}]);close(r.cost,60);assert.ok(r.complete);});
test('Profile weights expensive intervals by energy, not clock mean',()=>{const r=E.calculate(0,{profile:[{minutes:60,kwh:1},{minutes:60,kwh:6}]},[{start:0,end:H,price:1},{start:H,end:2*H,price:4}]);close(r.cost,25);assert.equal(r.uniform,false);});
test('Partial intervals and crossing midnight',()=>{const r=E.calculate(.5*H,{minutes:60,kwh:2},[{start:0,end:H,price:1},{start:H,end:2*H,price:3}]);close(r.cost,4);});
test('Negative prices are preserved',()=>{close(E.calculate(0,{minutes:60,kwh:3},[{start:0,end:H,price:-2}]).cost,-6);});
test('Missing prices do not produce a pretend total',()=>{const r=E.calculate(0,{minutes:60,kwh:2},[{start:0,end:.5*H,price:2}]);assert.equal(r.cost,null);close(r.missingMinutes,30);assert.equal(r.complete,false);});
test('Overlapping price intervals stop the calculation',()=>assert.throws(()=>E.normalizePrices([{start:0,end:H,price:2},{start:.5*H,end:2*H,price:2}]),/overlapper/));
test('Maximum power is a validation, never a default energy estimate',()=>{assert.throws(()=>E.validateProfile({minutes:60,kwh:8},7));assert.throws(()=>E.validateProfile({minutes:60,kwh:null},7));});
test('Missing prices during zero-consumption cooling do not add cost',()=>{const r=E.calculate(0,{profile:[{minutes:60,kwh:2},{minutes:60,kwh:0}]},[{start:0,end:H,price:3}]);assert.equal(r.complete,true);close(r.cost,6);});
test('Spring clock change is 23 hours, missing 02:30 rejected',()=>{const [a,b]=E.dayBounds('2026-03-29');assert.equal((b-a)/H,23);assert.throws(()=>E.localToEpoch('2026-03-29','02:30'));});
test('Autumn clock change is 25 hours, repeated time can be selected',()=>{const [a,b]=E.dayBounds('2026-10-25');assert.equal((b-a)/H,25);const x=E.localToEpoch('2026-10-25','02:30'),y=E.localToEpoch('2026-10-25','02:30','second');assert.ok(x.ambiguous);assert.equal(y.ms-x.ms,H);});
test('Impossible dates rejected, Danish clock independent of host TZ',()=>{assert.throws(()=>E.localToEpoch('2026-02-30','12:00'));assert.equal(E.localToEpoch('2026-09-25','07:30').ms,Date.parse('2026-09-25T05:30:00Z'));});
test('Optimizer uses entire continuous firing, not cheapest isolated hour',()=>{const o=E.optimize(0,2*H,{minutes:120,kwh:4},[0,1,2,3].map(i=>({start:i*H,end:(i+1)*H,price:[1,9,3,3][i]})),7,60);assert.equal(o.candidates[0].start,2*H);close(o.candidates[0].cost,12);});
test('Optimizer excludes incomplete and forecast candidates',()=>{const o=E.optimize(0,H,{minutes:60,kwh:2},[{start:0,end:H,price:1,forecast:true}],7,60);assert.equal(o.candidates.length,0);assert.equal(o.skipped,2);});
test('API adapter uses VAT-inclusive total, not base value',()=>{const rows=E.parseStromligning({prices:[{date:'2026-09-25T00:00:00+02:00',price:{total:2.5,value:2,unit:'DKK/kWh'}}]});assert.equal(rows[0].price,2.5);assert.equal(rows[0].end-rows[0].start,900000);});
test('API adapter rejects missing timezone, null total and unexpected units',()=>{assert.throws(()=>E.parseStromligning({prices:[{date:'2026-09-25T00:00:00',price:{total:2}}]}));assert.throws(()=>E.parseStromligning({prices:[{date:'2026-09-25T00:00:00Z',price:{total:null}}]}));assert.throws(()=>E.parseStromligning({prices:[{date:'2026-09-25T00:00:00Z',price:{total:2,unit:'EUR/MWh'}}]}));});
test('Forecasts are filtered from API results',()=>{assert.equal(E.parseStromligning({prices:[{date:'2026-09-25T00:00:00Z',price:{total:2},forecast:true}]}).length,0);});
test('Danish decimal comma parsed; blanks and booleans rejected',()=>{assert.equal(E.finite('2,5'),2.5);for(const x of ['',null,undefined,true,'no'])assert.throws(()=>E.finite(x));});
