/* Static family app. API credentials stay in GitHub Actions; browsers only read sanitized prices.json. */
(()=>{'use strict';
const BASE=new URL('./',document.baseURI),KEY='braending-github-'+BASE.pathname+'-',HOUR=3600000;
const h=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=id=>document.getElementById(id),num=(v,d=2)=>new Intl.NumberFormat('da-DK',{minimumFractionDigits:d,maximumFractionDigits:d}).format(v),money=v=>num(v)+' kr.';
const dur=m=>{const n=Math.round(m);return (Math.floor(n/60)?Math.floor(n/60)+' t ':'')+(n%60)+' min';};
const stamp=ms=>{const p=E.localParts(ms);return p.date.slice(8)+'.'+p.date.slice(5,7)+'. kl. '+p.time;};
const shortDate=ms=>{const p=E.localParts(ms);return Number(p.date.slice(8))+'.'+Number(p.date.slice(5));};
function read(key,fallback){try{return JSON.parse(localStorage.getItem(KEY+key))??fallback;}catch{return fallback;}}
function store(key,value){try{localStorage.setItem(KEY+key,JSON.stringify(value));return true;}catch{toast('Browseren kunne ikke gemme historikken.');return false;}}
const now=E.localParts(Math.ceil(Date.now()/900000)*900000);
const S={tab:'calc',program:3,cheapProgram:3,date:now.date,time:now.time,occurrence:'first',feed:null,prices:[],fetchError:'',loading:true,busy:false,result:null,optimal:null,error:'',modal:null,history:read('history-v5',read('history-v4',read('history',[])))};
function icon(name){const p={flame:'<path d="M12 2C14 8 20 9 20 15a8 8 0 1 1-16 0c0-4 3-7 5-9 0 4 1 5 3 6 2-3 2-6 0-10Z"/>',calc:'<rect x="4" y="3" width="16" height="18" rx="3"/><path d="M8 7h8M8 12h1m6 0h1M8 16h1m6 0h1"/>',price:'<path d="m3 17 5-6 4 3 8-10M15 4h5v5M3 21h18"/>',history:'<circle cx="12" cy="12" r="9"/><path d="M12 7v6l4 2"/>',settings:'<path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3"/><circle cx="15" cy="17" r="3"/>',share:'<path d="M12 15V3m-4 4 4-4 4 4M6 10H4v11h16V10h-2"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>'};return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+(p[name]||p.flame)+'</svg>';}
function toast(text){const el=$('toast');if(!el)return;el.textContent=text;el.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.style.display='none',5000);}
function source(){return '<p class="source"><a href="https://stromligning.dk" target="_blank" rel="noopener noreferrer">Data provided by Strømligning. stromligning.dk</a></p>';}
function header(){return '<header><div class="brand"><div class="brandmark">'+icon('flame')+'</div><div><strong>Brænding</strong><small>Keramik ovnen · Cerama SC 100</small></div></div><div class="header-actions"><span class="pill">Version 5.0</span><button class="icon-btn" data-action="share-app" aria-label="Del appen">'+icon('share')+'</button><button class="quiet" data-action="install">Appikon</button></div></header>';}
function nav(){return '<nav class="tabbar" aria-label="Hovedmenu">'+[['calc','Beregn','calc'],['cheap','Billigst','price'],['history','Brændinger','history'],['oven','Keramik ovnen','settings']].map(([id,title,ico])=>'<button class="tab'+(S.tab===id?' active':'')+'" data-tab="'+id+'" '+(S.tab===id?'aria-current="page"':'')+'>'+icon(ico)+h(title)+'</button>').join('')+'</nav>';}
function options(selected){let cat='';return E.ALL_PROGRAMS.map(p=>{const group=cat!==p.category?(cat?'</optgroup>':'')+'<optgroup label="'+h(p.category)+'">':'';cat=p.category;return group+'<option value="'+p.id+'"'+(p.id===selected?' selected':'')+'>P'+p.id+' · '+h(p.name)+' · '+p.temp+' °C</option>';}).join('')+'</optgroup>';}
function programSelect(id,label,selected){return '<div class="field full"><label for="'+id+'">'+label+'</label><select id="'+id+'">'+options(selected)+'</select></div>';}
function field(id,label,type,value,extra=''){return '<div class="field"><label for="'+id+'">'+label+'</label><input type="'+type+'" id="'+id+'" value="'+h(value??'')+'" '+extra+'></div>';}
function intro(title,desc){return '<section class="intro"><p class="eyebrow">Keramik ovnen</p><h1>'+title+'</h1><p class="muted">'+desc+'</p></section>';}
function usablePriceArray(throwOnMissing=true){
 if(!S.feed?.verified||S.feed.priceBasis!=='variable-total-dkk-kwh-including-vat'||!S.prices.length){if(throwOnMissing)throw Error('Der er endnu ingen brugbare Strømligning-priser. Se Keramik ovnen → Strømligning.');return [];}
 const fetched=Date.parse(S.feed.fetchedAt),old=!Number.isFinite(fetched)||Date.now()-fetched>12*HOUR;
 return S.prices.filter(p=>!p.forecast||!old);
}
function priceBoard(){
 if(S.loading)return '<section class="price-board loading"><div><p class="eyebrow">Elpris time for time</p><h2>Henter Strømligning-priser…</h2></div></section>';
 const ps=usablePriceArray(false),hours=E.hourlyPrices(ps,Date.now(),168),f=S.feed;
 if(!hours.length)return '<section class="price-board unavailable"><div><p class="eyebrow">Elpris time for time</p><h2>Ingen prisdata endnu</h2><p class="muted">'+h(S.fetchError||f?.message||'Strømligning-forbindelsen er ikke færdigopsat.')+'</p><button class="quiet" data-action="refresh">Prøv igen</button>'+source()+'</div></section>';
 const nowMs=Date.now(),future=hours.filter(x=>x.end>nowMs),count=future.length;
 const current=future.find(x=>x.start<=nowMs&&x.end>nowMs)||future[0];
 const next24=future.filter(x=>x.start<nowMs+24*HOUR),cheap24=next24.length?next24.reduce((a,b)=>b.price<a.price?b:a):null;
 const maxPrice=Math.max(3.25,...future.map(x=>Math.max(0,x.price)))*1.04;
 const cards=future.map((x,i)=>{
  const p=E.localParts(x.start),band=E.priceBand(x.price),height=Math.max(5,Math.min(100,Math.max(0,x.price)/maxPrice*100));
  const isCurrent=x===current,aria=shortDate(x.start)+' kl. '+p.time+', '+num(x.price,2)+' kr. pr. kWh'+(x.forecast?', prognose':'');
  return '<div class="price-hour '+band+(isCurrent?' current':'')+'" aria-label="'+h(aria)+'" title="'+h(aria)+'"><span class="price-date">'+h(shortDate(x.start))+'</span><b class="price-value">'+num(x.price,2)+'</b><div class="bar-track"><i class="price-bar" style="--bar-height:'+height.toFixed(1)+'%"></i></div><strong class="price-time">'+h(p.time)+'</strong>'+(x.forecast?'<span class="forecast-badge" title="Prognose">P</span>':'<span class="forecast-spacer" aria-hidden="true"></span>')+'</div>';
 }).join('');
 const currentSummary=current?'<div class="price-summary"><span>Nu</span><strong>'+num(current.price,2)+' kr.</strong><small>'+h(E.localParts(current.start).time)+' · '+h(shortDate(current.start))+'</small></div>':'';
 const cheapSummary=cheap24?'<div class="price-summary"><span>Billigst næste 24 t</span><strong>'+num(cheap24.price,2)+' kr.</strong><small>'+h(E.localParts(cheap24.start).time)+' · '+h(shortDate(cheap24.start))+'</small></div>':'';
 return '<section class="price-board"><div class="price-board-head"><div><p class="eyebrow">Elpris time for time</p><h2>'+h(E.naturalPriceRangeLabel(count))+'</h2><p class="muted small">Samlet variabel pris inkl. moms, tariffer og tillæg.</p></div><button class="quiet" data-action="refresh">Opdater</button></div><div class="price-summaries">'+currentSummary+cheapSummary+'</div><div class="price-chart-wrap"><div class="price-chart" aria-label="Søjlediagram over elpriser time for time">'+cards+'</div></div><p class="price-swipe-hint">Stryg vandret for at se flere timer →</p><div class="price-legend" aria-label="Prisniveauer"><span><i class="band-low"></i>≤ 1,00 kr.</span><span><i class="band-medium"></i>1,01–2,00</span><span><i class="band-high"></i>2,01–3,00</span><span><i class="band-very-high"></i>&gt; 3,00</span><span><i class="forecast-key">P</i>prognose</span><span>Hentet '+h(stamp(Date.parse(f.fetchedAt)))+'</span></div>'+source()+'</section>';
}
function programInfo(id){const p=E.buildProgram(id);return '<div class="program-meta"><span>'+h(dur(p.minutes))+' beregningsvarighed</span><span>'+num(p.kwh,1)+' kWh · standardestimat</span></div><p class="note">Fast metode: 7,0 kW × '+num(p.minutes/60,2)+' timer × 0,50 = '+num(p.kwh,2)+' kWh. '+h(p.coolingText)+'</p>'+(p.note?'<p class="safety">'+h(p.note)+'</p>':'');}
function calcPage(){return intro('Hvad koster<br>din brænding?','Vælg startdato, starttid og program. Prisen beregnes automatisk med Strømlignings timepriser og samme energiformel for alle fabriksprogrammer.')+'<div class="grid"><div class="stack"><section class="card"><div class="card-header"><h2>Planlæg brændingen</h2><span class="pill">SC 100</span></div><form id="calc-form"><div class="form-grid">'+programSelect('calc-program','Program',S.program)+field('calc-date','Startdato','date',S.date,'required')+field('calc-time','Starttid','time',S.time,'required')+'</div>'+programInfo(S.program)+'<details><summary>Ved skift til vintertid</summary><label for="occurrence">Gentaget klokkeslæt</label><select id="occurrence"><option value="first"'+(S.occurrence==='first'?' selected':'')+'>Første forekomst</option><option value="second"'+(S.occurrence==='second'?' selected':'')+'>Anden forekomst</option></select></details><button class="primary wide" type="submit" '+(S.busy?'disabled':'')+' style="margin-top:20px">'+(S.busy?'Beregner…':'Beregn prisen')+'</button></form></section></div><div class="stack"><div class="result-column">'+(S.result?resultCard(S.result):'')+'</div></div></div>';}
function optimizerForm(){return '<section class="card optimize-card"><p class="eyebrow">De næste 3 dage</p><h2>Hvornår er det billigste tidspunkt?</h2><p class="muted small" style="margin:14px 0">Vælg program. Beregneren tester alle starter minut for minut i de næste 72 timer. Du får den billigste start og et separat alternativ mellem kl. 06.30 og 21.30.</p><form id="cheap-form">'+programSelect('cheap-program','Program',S.cheapProgram)+'<button class="primary wide" type="submit" style="margin-top:17px" '+(S.busy?'disabled':'')+'>'+(S.busy?'Sammenligner…':'Find billigste tidspunkt')+'</button></form>'+programInfo(S.cheapProgram)+'</section>';}
function cheapPage(){return intro('Hvornår skal<br>ovnen starte?','Find den billigste samlede brænding i de næste tre døgn ud fra samme faste energimodel og de tilgængelige Strømligning-priser.')+'<div class="grid"><div class="stack">'+optimizerForm()+'</div><div class="stack recommendations">'+(S.optimal?optimalResults():'')+'</div></div>';}
function resultCard(r){if(!r.complete)return '<section class="card"><h2>Priserne dækker ikke hele brændingen</h2><p style="margin-top:14px">Der mangler '+h(dur(r.missingMinutes))+' prisdata. Derfor vises ingen samlet pris.</p>'+source()+'</section>';
 return '<section class="card result" aria-live="polite"><p class="eyebrow">'+h(r.basisLabel)+(r.forecast?' · med prognose':'')+'</p><h2 style="margin-top:10px">P'+r.programId+' · '+h(r.programName)+'</h2><div class="amount">'+num(r.cost)+'<span>kr.</span></div><div class="metrics"><div><small>Start</small><strong>'+h(stamp(r.start))+'</strong></div><div><small>Beregningsvindue slutter</small><strong>'+h(stamp(r.end))+'</strong></div><div><small>Estimeret forbrug</small><strong>'+num(r.kwh,1)+' kWh</strong></div><div><small>Effektiv gennemsnitseffekt</small><strong>'+num(r.effectiveKw,1)+' kW</strong></div></div><p class="note">Forbrug = 7,0 kW × '+num(r.minutes/60,2)+' timer × 0,50. Timeprisen vægtes over hele beregningsvinduet.</p><div class="cooling-note"><b>Afkøling</b><p>'+h(r.coolingText)+'</p></div>'+(r.forecast?'<p class="forecast-note">Indeholder prognosepriser. Pris og rangering kan ændre sig, når endelige priser offentliggøres.</p>':'')+'<div class="btn-row"><button class="quiet" data-action="save">Gem brænding</button><button class="quiet" data-action="share-result">Del</button></div>'+source()+'</section>';}
function candidate(label,r){if(!r)return '<div class="choice"><div><b>'+label+'</b><small>Ikke nok prisdata til et fuldt forslag</small></div></div>';return '<button class="choice '+(label==='Bedste pris'?'best':'')+'" data-candidate="'+(label==='Bedste pris'?'best':'alternative')+'"><div><b>'+label+'</b><small>'+h(stamp(r.start))+' · '+num(r.kwh,1)+' kWh'+(r.forecast?' · prognose':'')+'</small></div><strong>'+money(r.cost)+'</strong></button>';}
function optimalResults(){const o=S.optimal;if(!o)return '';return '<section class="card"><p class="eyebrow">Forslag</p><h2 style="margin-top:8px">Billigste start</h2>'+candidate('Bedste pris',o.best)+candidate('Alternativ',o.alternative)+'<p class="note">Alternativet ligger mindst 60 minutter fra bedste forslag og starter altid mellem kl. 06.30 og 21.30. '+(o.allStartsCovered?'Alle starter i de 72 timer havde fuld prisdækning.':'Nogle starter kunne ikke beregnes, fordi prisdata ikke dækkede hele brændingen.')+'</p>'+source()+'</section>';}
function historyPage(){const rows=S.history.map(r=>'<article class="history-item"><div class="row"><div><p class="eyebrow">P'+h(r.programId)+' · '+h(r.programName)+'</p><h3>'+h(stamp(r.start))+'</h3><small class="muted">'+h(r.note||'Ingen note')+'</small></div><strong>'+money(r.cost)+'</strong></div><div class="actions"><button class="quiet" data-share="'+h(r.id)+'">Del</button><button class="quiet" data-delete="'+h(r.id)+'">Slet</button></div></article>').join('');return intro('Brændinger','Historikken gemmes kun på denne telefon/browser.')+'<section class="card">'+(rows||'<div class="empty"><h2>Ingen gemte brændinger</h2><p class="muted">Gem en beregning, når du vil huske den.</p></div>')+'</section>';}
function ovenPage(){return intro('Keramik ovnen','Cerama SC 100 · 99 liter · 7,0 kW · G20-20 med 12 fabriksprogrammer.')+'<div class="grid"><div class="stack"><section class="card"><h2>Én fast beregning</h2><p style="margin-top:14px">Alle brændinger bruger samme metode:</p><div class="formula">7,0 kW × programtid × 0,50 = estimeret kWh</div><p>Ved skiftende elpriser fordeles dette som en effektiv gennemsnitseffekt på <b>3,5 kW</b> gennem beregningsvinduet, og hvert prisinterval fra Strømligning vægtes efter sin varighed.</p><p class="note">Det er et standardestimat, ikke en elmålermåling. Metoden følger Skutts offentliggjorte beregningsformel med adjustment factor og passer meget tæt på Nabertherms 100-liters, 7 kW reference: Cerama P2 + P4 giver 56,6 kWh med modellen; Nabertherms TOP 100-eksempel angiver 56,7 kWh for bisque + glaze.</p><div class="source-links"><a href="https://skutt.com/skutt-resources/resources-just-for-you/studio/faqs/" target="_blank" rel="noopener">Skutt: beregningsformel</a><a href="https://nabertherm.com/sites/default/files/2024-04/artscrafts_english_0.pdf" target="_blank" rel="noopener">Nabertherm: TOP 100-reference</a></div></section><section class="card"><h2>Afkøling</h2><p style="margin-top:14px">Cerama-manualen angiver ikke en fast naturlig afkølingstid efter brændingen. Derfor lægger appen ikke en opdigtet tid på.</p><p>P8-P12 indeholder også en naturlig SkIP-afkølingsfase inde i programmet. Den bruger ingen beregnet energi, men dens varighed er ikke oplyst. De øvrige styrede faser er med i beregningsvarigheden.</p></section></div><div class="stack"><section class="card"><h2>Fabriksprogrammer</h2><div class="program-table">'+E.ALL_PROGRAMS.map(p=>{const b=E.buildProgram(p.id);return '<div><b>P'+p.id+'</b><span>'+h(p.name)+'</span><small>'+p.temp+' °C · '+dur(b.minutes)+' · '+num(b.kwh,1)+' kWh</small></div>';}).join('')+'</div></section><section class="card"><h2>Strømligning</h2><dl class="connection"><dt>Prisforbindelse</dt><dd>'+h(S.feed?.verified?'Prisfil modtaget':'Ikke tilsluttet')+'</dd><dt>Seneste hentning</dt><dd>'+h(S.feed?.fetchedAt?stamp(Date.parse(S.feed.fetchedAt)):'Ingen hentning')+'</dd><dt>Prisgrundlag</dt><dd>Samlet variabel pris fra <code>price.total</code> inkl. moms, tariffer og tillæg. Faste abonnementer er ikke fordelt.</dd><dt>Verificering</dt><dd>'+h(S.feed?.basisVerification?.method==='api-components-sum-to-price.total'?'Automatisk verificeret mod API-komponenterne':'Ikke verificeret')+'</dd><dt>Fremtidige priser</dt><dd>'+E.hourlyPrices(usablePriceArray(false),Date.now(),168).length+' komplette timer i prisfilen</dd></dl><button class="quiet" data-action="refresh" style="margin-top:16px">Hent seneste prisfil</button>'+source()+'</section></div></div>';}
function modal(){if(!S.modal)return '';return '<div class="modal-backdrop"><div class="modal" role="dialog" aria-modal="true"><div class="card-header"><h2>'+(S.modal==='save'?'Gem brænding':'Føj til hjemmeskærm')+'</h2><button class="icon-btn" data-action="close" aria-label="Luk">'+icon('close')+'</button></div>'+(S.modal==='save'?'<form id="save-form"><label for="save-note">Note</label><textarea id="save-note" maxlength="1000" placeholder="Fx glasur, indhold eller hvem der brænder"></textarea><button class="primary wide" style="margin-top:15px">Gem</button></form>':'<p>På iPhone: Åbn appens link i Safari, tryk Del, og vælg Føj til hjemmeskærm. På Android: vælg Installer app eller Føj til startskærm.</p>')+'</div></div>';}
function render(){const body=S.tab==='calc'?calcPage():S.tab==='cheap'?cheapPage():S.tab==='history'?historyPage():ovenPage();$('root').innerHTML='<div class="app">'+header()+priceBoard()+(S.error?'<p class="error" role="alert" style="margin-top:18px">'+h(S.error)+'</p>':'')+body+'<footer class="foot">Brænding 6.0.0 · Dansk tid (Europe/Copenhagen). Appen starter eller styrer aldrig ovnen.</footer></div>'+nav()+modal();}
function updateInputs(){if($('calc-date'))S.date=$('calc-date').value;if($('calc-time'))S.time=$('calc-time').value;if($('calc-program'))S.program=Number($('calc-program').value);if($('cheap-program'))S.cheapProgram=Number($('cheap-program').value);if($('occurrence'))S.occurrence=$('occurrence').value;}
async function loadPrices(){S.loading=true;S.fetchError='';try{const r=await fetch(new URL('data/prices.json',BASE),{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('Prisfilen kunne ikke hentes.');const text=await r.text();if(text.length>8000000)throw Error('Prisfilen er for stor.');const f=JSON.parse(text);if(f.verified===true&&f.priceBasis!=='variable-total-dkk-kwh-including-vat')throw Error('Prisgrundlaget er ikke bekræftet.');S.prices=E.normalizePrices(f.prices||[]);S.feed=f;store('feed-v5',f);}catch(e){S.fetchError='Seneste prisfil kunne ikke hentes. '+e.message;const old=read('feed-v5',read('feed-v4',null));if(old?.priceBasis==='variable-total-dkk-kwh-including-vat'){S.feed=old;try{S.prices=E.normalizePrices(old.prices);}catch{S.prices=[];}}}finally{S.loading=false;}}
function usablePrices(){const p=usablePriceArray(true);if(!p.length)throw Error('Der er ingen gyldige prisintervaller.');return p;}
async function runCalculation(){updateInputs();S.error='';S.result=null;try{const p=E.buildProgram(S.program),start=E.localToEpoch(S.date,S.time,S.occurrence);S.busy=true;render();await new Promise(r=>setTimeout(r,15));S.result=E.calculate(start.ms,p,usablePrices());if(start.ambiguous)toast('Gentaget klokkeslæt: '+(S.occurrence==='second'?'anden':'første')+' forekomst.');}catch(e){S.error=e.message;}finally{S.busy=false;render();if(S.result&&innerWidth<721)document.querySelector('.result-column')?.scrollIntoView({behavior:'smooth',block:'start'});}}
async function runCheapest(){updateInputs();S.error='';S.optimal=null;try{const p=E.buildProgram(S.cheapProgram);S.busy=true;render();await new Promise(r=>setTimeout(r,20));S.optimal=E.findCheapest(p,usablePrices(),Date.now());}catch(e){S.error=e.message;}finally{S.busy=false;render();}}
async function share(text,url){try{if(navigator.share)await navigator.share({title:'Brænding',text,...(url?{url}:{})});else if(navigator.clipboard){await navigator.clipboard.writeText(text+(url?'\n'+url:''));toast('Kopieret til udklipsholder.');}else prompt('Kopiér teksten:',text+(url?'\n'+url:''));}catch(e){if(e.name!=='AbortError')toast('Delingen kunne ikke gennemføres.');}}
function resultText(r){return 'Keramik ovnen · P'+r.programId+' '+r.programName+'\nStart '+stamp(r.start)+'\nPris '+money(r.cost)+'\nEstimeret forbrug '+num(r.kwh,1)+' kWh\nStandardmodel: 7,0 kW × programtid × 0,50'+(r.forecast?'\nIndeholder prognosepriser.':'')+'\n'+r.coolingText+'\nData provided by Strømligning. https://stromligning.dk';}
$('root').addEventListener('submit',async ev=>{ev.preventDefault();S.error='';try{if(ev.target.id==='calc-form')return await runCalculation();if(ev.target.id==='cheap-form')return await runCheapest();if(ev.target.id==='save-form'){if(!S.result?.complete)throw Error('Beregn en fuld pris først.');const record={...S.result,id:crypto.randomUUID(),note:$('save-note').value.trim(),savedAt:new Date().toISOString()};delete record.breakdown;const history=[record,...S.history].slice(0,100);if(store('history-v5',history))S.history=history;S.modal=null;S.tab='history';render();toast('Brændingen er gemt.');}}catch(e){S.error=e.message;render();}});
$('root').addEventListener('click',async ev=>{const b=ev.target.closest('button');if(!b||b.disabled)return;try{updateInputs();S.error='';if(b.dataset.tab){S.tab=b.dataset.tab;render();window.scrollTo(0,0);return;}if(b.dataset.candidate){const r=S.optimal?.[b.dataset.candidate];if(!r)return;const local=E.localParts(r.start);S.program=r.programId;S.date=local.date;S.time=local.time;S.result=E.calculate(r.start,E.buildProgram(r.programId),usablePrices());S.tab='calc';render();window.scrollTo(0,0);return;}if(b.dataset.delete){if(confirm('Slet brændingen fra denne browser?')){const rows=S.history.filter(r=>r.id!==b.dataset.delete);if(store('history-v5',rows))S.history=rows;render();}return;}if(b.dataset.share){const r=S.history.find(r=>r.id===b.dataset.share);if(r)await share(resultText(r));return;}const a=b.dataset.action;if(a==='refresh'){S.result=null;S.optimal=null;await loadPrices();render();toast(S.fetchError||'Seneste prisfil er hentet.');}if(a==='share-app')await share('Brænding - Keramik ovnen',BASE.href);if(a==='install'){S.modal='install';render();}if(a==='close'){S.modal=null;render();}if(a==='save'){S.modal='save';render();$('save-note')?.focus();}if(a==='share-result'&&S.result?.complete)await share(resultText(S.result));}catch(e){S.error=e.message;render();}});
$('root').addEventListener('change',ev=>{updateInputs();if(ev.target.id==='calc-program'){S.result=null;render();}if(ev.target.id==='cheap-program'){S.optimal=null;render();}if(['calc-date','calc-time','occurrence'].includes(ev.target.id)){S.result=null;render();}});
$('root').addEventListener('input',ev=>{if(['calc-date','calc-time'].includes(ev.target.id)){updateInputs();S.result=null;}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&S.modal){S.modal=null;render();}});
render();loadPrices().then(render);
})();
